### PR TITLE
Add redirectDefaultLang option

### PR DESCRIPTION
**Pull request by orblazer**
Add an option for redirect or not when the url is `/` to `/<defaultLang>`

The options added : 
- **redirectDefaultLang** : Redirect default lang to localized url (eg: redirect `/` to `/en` when `en` is your default language)

Thanks.

### CODE REVIEW

**Comment by njam** [comment]
@orblazer I've implemented a fixture-based test for this functionality and pushed it to the branch `noredir-test`. You can find the assertions in [`fixture-noredir.test.js`](https://github.com/njam/nuxt-i18n-module/blob/noredir-test/test/fixture-noredir.test.js).

Please merge it into the pull request, and make sure the tests pass.
If you disagree with the assertions, let me know!

**Comment by orblazer** [comment]
Hello @njam after long time with no activity i have make the test for this PR.

**Comment by njam** [comment]
@orblazer very nice, thanks!

I believe there is a small issue in that the code still generates an alt-link with `hreflang="x-default"`, although there's no _language-independent_ version available. I will fix it in a separate commit.

**Comment by orblazer** [comment]
Ok ok, thanks @njam

**Pull request merged**
