### PR TITLE
Changement for V0.0.5

### PR DESCRIPTION
**Pull request by orblazer**
Hello, i have remake my first PR #1 with the last version and better code.

The changes :
- Add an option for default language (`defaultLanguage`)
- Add an option for redirect if is default language (`redirectDefaultLang`)
- Add vue component for switch between lang (`nuxt-i18n-link`)
- Add eslint
- Improve detection of language

Thanks you.

### CODE REVIEW

**Comment by njam** [comment]
@orblazer thank you! I will take a look at this over the next few days.
@christopheschwyzer maybe you have some feedback, especially in regard to the new component `NuxtI18nLink.vue`?

**Comment by stophecom** [comment]
- eslint ftw!
- About the language switcher component. I don't think it's necessary - should be as easy as:
```vue
     <nuxt-link  :to="{ params: {lang: 'DE'} }">DE</nuxt-link>
```
To switch to "DE" in the above example. Maybe add it to the description.

**Comment by orblazer** [comment]
Ok, if you want, i can remove this component from here

**Comment by njam** [comment]
@orblazer thanks for your contribution! I was looking at the code in more detail today, and here's my feedback:
- **defaultLanguage**: makes totally sense
- **redirectDefaultLang**: the idea of using the "plain" URL (like `/foo`) for the default language is valid. But the current implementation only disables the redirect from the "plain" URL. The "plain" URL uses `hreflang=x-default` which is for the page that ["doesn’t target any specific language or locale and is the default page when no other page is better suited."](https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html). So I think the correct thing to do would be to *completely replace* the language-specific route (e.g. `/en/foo`) with the "plain" on (`/foo`), if this setting is set. We should also make sure that any links to pages in the default language then link to the "plain" URL (e.g. in `NuxtI18nLink.vue`).
- **ESLint**: I cannot get the linting to work, but maybe I'm doing something wrong. I tried running `node_modules/.bin/eslint 'src/**'`, but I get errors for those template lines, like `const options = <%= serialize(options) %>` in `middleware.js`. How should the linting be executed? Could you add it to the CI (`.travis.yml`)?
- **NuxtI18nLink.vue**: I agree with Christophe that this is not necessarily needed, but it also doesn't hurt. If you want to add it, please add documentation and if possible add it to the tests. What do you think about adding a *language switcher* component?
- **Improve detection of language**: makes sense!

It would be easier if you could submit individual pull requests for each feature. That way we can have separate discussions and reviewing the change is much easier.
What do you think?

**Comment by orblazer** [comment]
Ok @njam 
I can move vue element to an other PR. and about that, yes i can make test and write documentation.
For the language switcher component you think an element like dropdown ?
For `redirectDefaultLang`if i have uderstand is just to remove the alternative for the `defaultLanguage`. Like :
If the `defaultLanguage` is set to `en` the alternative link have only `de` and default tag (when `languages` is set to: `['en', 'de']`

**Comment by njam** [comment]
> For `redirectDefaultLang`if i have uderstand is just to remove the alternative for the `defaultLanguage`. Like :
If the `defaultLanguage` is set to `en` the alternative link have only `de` and default tag (when `languages` is set to: `['en', 'de']`

Yes exactly. Given `['en', 'de']` and a page "foo" there should be *only* 2 routes:
- `/foo`: The English version (default language), with `hreflang="en"`
- `/de/foo`: The German version, with `hreflang="de"`

And any links generated for the English version should point to the correct route.
Let me know if you disagree!

**Comment by orblazer** [comment]
In same time of that i can propose add `lang` attr to `html` tag for the SEO

**Comment by orblazer** [comment]
I close this PR because is now useless, all change is remake on others PR.

**Comment by njam** [comment]
@orblazer thanks for the contributions!

**Pull request closed without merging**
